config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get 'user/index'

  devise_for :users

  get 'cities/:city_id/post/new' => "post#new", as: "post_new"

  post 'cities/:city_id/post' => "post#create", as: "post_create"

  get 'posts/edit/:post_id' => "post#edit", as: "post_edit"

  get 'posts/:post_id' => "post#show", as: "post_show"

  put 'posts/:post_id' => "post#update", as: "post_update"

  delete 'posts/:post_id' => "post#delete", as: "post_delete"

  get 'city/index'

  get 'cities/:city_id' => "city#show", as: "city_show"

  get 'static_pages/home'

  get 'users' => "user#index"

  get 'users/profile' => "user#profile", as: "user_profile"

  get 'users/profile/edit' => "user#edit", as: "user_edit"

  get 'users/:user_id' => "user#show", as: "user_show"

  put 'users/:user_id' => "user#update", as: "user_update"
  
  get 'users/:user_id/following' => "user#following", as: "user_following"

  get 'users/:user_id/followers' => "user#followers", as: "user_followers"

  get 'posts/:post_id/comments/new' => "comments#new", as: "comment_new"

  post 'posts/:post_id/comments' => "comments#create", as: "comment_create"

  delete 'posts/:post_id/comments/:comment_id' => "comments#delete", as: "comment_delete"

  resources :bonds, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
  belongs_to :user

  
  validates :content,
            presence: true,
            length: {maximum: 250}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :comment_params
  before_action :comment_delete_params, only: [:delete]

  def new
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(comment_create_params)
    if @comment.save
      redirect_to post_show_path(@post)
    else
      render :new
    end
    
  end
  
  def delete
    @comment.destroy
    redirect_to post_show_path(@post)
  end
  
  private
    def comment_params
      @post = Post.find(params[:post_id])
    end

    def comment_create_params
      params.require(:comment)
            .permit(:content)
            .merge(user_id: current_user.id, post_id: @post.id)
    end

    def comment_delete_params
      @comment = Comment.find(params[:comment_id])
    end
    
    

    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<h4>ADD A COMMENT</h4>

<%= bootstrap_form_for(@comment, inline_errors: false, url: comment_create_path) do |f| %>
  <%= f.alert_message "There was a problem creating your comment:" %>
  <%= f.text_field :content %>
  <%= f.submit "Create Comment", data: {
                  :'sweet-alert-confirm' => "Are you sure you want to create this comment?",
                  :'confirm-button-text' => 'Create',
                  :'cancel-button-text' => 'Cancel',
                  :'confirm-button-color' => '#5CB85C',
                  :'sweet-alert-type' => 'success',
                  text: 'This cannot be edited later.'
                  } %>

<% end %>