config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get 'user/index'

  devise_for :users

  get 'cities/:city_id/post/new' => "post#new", as: "post_new"

  post 'cities/:city_id/post' => "post#create", as: "post_create"

  get 'posts/edit/:post_id' => "post#edit", as: "post_edit"

  get 'posts/:post_id' => "post#show", as: "post_show"

  put 'posts/:post_id' => "post#update", as: "post_update"

  delete 'posts/:post_id' => "post#delete", as: "post_delete"

  get 'city/index'

  get 'cities/:city_id' => "city#show", as: "city_show"

  get 'static_pages/home'

  get 'users' => "user#index"

  get 'users/profile' => "user#profile", as: "user_profile"

  get 'users/profile/edit' => "user#edit", as: "user_edit"

  get 'users/:user_id' => "user#show", as: "user_show"

  put 'users/:user_id' => "user#update", as: "user_update"
  
  get 'users/:user_id/following' => "user#following", as: "user_following"

  get 'users/:user_id/followers' => "user#followers", as: "user_followers"

  get 'posts/:post_id/comments/new' => "comments#new", as: "comment_new"

  post 'posts/:post_id/comments' => "comments#create", as: "comment_create"

  delete 'posts/:post_id/comments/:comment_id' => "comments#delete", as: "comment_delete"

  resources :bonds, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'
end

app/models/city.rb
class City < ApplicationRecord
  include FriendlyId
  validates_uniqueness_of :name
  before_save :downcase_name


  friendly_id :name_downcase

  has_many :posts, dependent: :destroy



  def downcase_name
    self.name_downcase = self.name.downcase
  end
  

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  before_action :city_params, only: [:show]

  def index
  end

  def show
    @posts = @city.posts.order('created_at DESC')
    @posts = @posts.paginate(:page => params[:page], per_page: 10)
  end

  private
    def city_params
      @city = City.friendly.find(params[:city_id].to_s.downcase)
      # @city = City.find()
    end
    
end

app/helpers/city_helper.rb
module CityHelper
end

app/views/city/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="span8 welcome-image">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" ></li>
        <li data-target="#myCarousel" data-slide-to="1" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item">
          <a href="/cities/London"><img src="http://i.imgur.com/mJIHxSi.jpg" alt="London">
          <div class="carousel-caption d-none d-md-block">
        <h1 class="carousel-header">LONDON</h1>
        <p class="carousel-body">UNITED KINGDOM</p>
        </div>
        </a>
        </div>

        <div class="item active">
          <a href="/cities/Atlanta"><img src="http://i.imgur.com/TnuIg5U.jpg" alt="Atlanta">
        <div class="carousel-caption d-none d-md-block">
        <h1 class="carousel-header">ATLANTA</h1>
        <p class="carousel-body">GEORGIA</p>
      </div>
      </a>
      </div>
      
        <div class="item">
          <a href="/cities/San Francisco"><img src="http://i.imgur.com/PCGyG1O.jpg" alt="San Francisco">
        <div class="carousel-caption d-none d-md-block">
        <h1 class="carousel-header">SAN FRANCISCO</h1>
        <p class="carousel-body">CALIFORNIA</p>
      </div>
      </a>
    </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

</body>
</html>

app/views/city/show.html.erb
<div class="city-header">
  <h1 class="city-header--text">
    <%= @city.name %>
  </h1>
  <button type="button" class="btn btn-default header-button">
    <%= link_to "New Post", post_new_path(@city.id) %>
  </button>
</div>
<div class="city-header--image">
  <% if @city.img_url %>
      <%= image_tag(@city.img_url, :class=> "city_img") %>
  <% end %>
</div>

<ul>
    <% @posts.each do |post| %>
      <%= render "post/post", collection: @post = post %>
    <% end %>
    <br>
    <%= will_paginate @posts, :class => 'apple_pagination' %>

 </ul>