config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get 'user/index'

  devise_for :users

  get 'cities/:city_id/post/new' => "post#new", as: "post_new"

  post 'cities/:city_id/post' => "post#create", as: "post_create"

  get 'posts/edit/:post_id' => "post#edit", as: "post_edit"

  get 'posts/:post_id' => "post#show", as: "post_show"

  put 'posts/:post_id' => "post#update", as: "post_update"

  delete 'posts/:post_id' => "post#delete", as: "post_delete"

  get 'city/index'

  get 'cities/:city_id' => "city#show", as: "city_show"

  get 'static_pages/home'

  get 'users' => "user#index"

  get 'users/profile' => "user#profile", as: "user_profile"

  get 'users/profile/edit' => "user#edit", as: "user_edit"

  get 'users/:user_id' => "user#show", as: "user_show"

  put 'users/:user_id' => "user#update", as: "user_update"
  
  get 'users/:user_id/following' => "user#following", as: "user_following"

  get 'users/:user_id/followers' => "user#followers", as: "user_followers"

  get 'posts/:post_id/comments/new' => "comments#new", as: "comment_new"

  post 'posts/:post_id/comments' => "comments#create", as: "comment_create"

  delete 'posts/:post_id/comments/:comment_id' => "comments#delete", as: "comment_delete"

  resources :bonds, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :city
  belongs_to :user

  has_many :comments

  # validates_presence_of :title
  validates_presence_of :content
  validates :title,
            presence: true,
            length: {maximum: 200}

  
  def time_difference
    diff = Time.new - self.created_at
    diff_secs = diff.round
    diff_days = (diff / 86400).round
    diff_hours = (diff / 3600).round
    diff_mins = (diff / 60).round
    if diff_days >= 2
      return "Written #{diff_days} days ago."
    elsif diff_hours >= 1
      return "Written #{diff_hours} hours ago."
    elsif diff_mins >= 1
      return "Written #{diff_mins} minutes ago."
    else
      return "Written #{diff_secs} seconds ago."
    end
    
  end
  
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :delete]
  before_action :post_params, only: [:show, :edit, :update, :delete]
  before_action :create_params, only: [:create, :new]
  def show

  end

  def edit

  end

  def new
    @post = Post.new
  end

  def update
    if @post.update(post_update_params)
      redirect_to post_show_path(@post)
    else
      render :edit
    end
  end

  def create
    @post = Post.new(post_create_params)
    if @post.save
      redirect_to city_show_path(@city.id)
    else
      render :new
    end

  end

  def delete
    @post.destroy
    redirect_back(fallback_location: root_path)
  end

  def post_create_params
    params.require(:post)
      .permit(:title, :content)
      .merge(user_id: current_user.id, city_id: params[:city_id])
  end

  def post_update_params
    params.require(:post)
      .permit(:title, :content)
      .merge(user_id: current_user.id, city_id: @post.city_id)
  end
  


  private
    def post_params
      @post = Post.find(params[:post_id])
    end

    def create_params
      @city = City.find(params[:city_id])
    end


end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/_post.html.erb
<div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="feed feed-body">
          <div class="list-group">
                  <li class="list-group-item">
                    <div class="feed feed-picture col-lg-4 col-md-4 col-sm-4 col-xs-4">
                      <%= image_tag(@post.user.img_url, :class=> "profile_img_feed img-rounded img-responsive") %>
                    </div>
                    <div class="feed-body">
                      <%= link_to user_show_path(@post.user) do %>
                          <h3><%= @post.user.username %></h3>
                      <% end %>
                      <%= link_to post_show_path(@post.id) do %>
                          <h4><%= @post.title %></h4>
                      <% end %>
                      <br>
                      <p><%= @post.content %></p>
                      <br>
                      <div class="postFooter">
                        <span class="postCity"><%= @post.city.name %>, <%= @post.city.country %> </span>
                          <br>
                        <span class="postComments">Number of comments: <%= @post.comments.length %>,   <%= @post.time_difference %></span>

                        <% if user_signed_in? %>
                            <% if @post.user_id == current_user.id %>

                                <%= link_to post_edit_path(@post.id) do %>
                                    <i class="fa fa-pencil fa-2x" aria-hidden="true"></i>
                                <% end %>

                                <%= link_to ('<i class="fa fa-trash fa-2x" aria-hidden="true"></i>').html_safe, post_delete_path(@post.id),
                                            method: 'delete',
                                            data: {
                                                :'sweet-alert-confirm' => "Are you sure you want to delete #{@post.title}?",
                                                :'confirm-button-text' => 'Delete',
                                                :'cancel-button-text' => 'Cancel',
                                                :'confirm-button-color' => '#D9534F',
                                                :'sweet-alert-type' => 'error',
                                                text: 'This cannot be undone.'
                                            } %>

                            <% end %>
                            <%= link_to comment_new_path(@post.id) do %>
                              <i class="fa fa-plus-square fa-2x" aria-hidden="true"></i>Add Comment
                            <% end %>
                        <% end %>
                    </div>
                  </li>
          </div>
        </div>
      </div>
    </div>

app/views/post/_post_minimal.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="feed feed-body">
      <div class="list-group">
        <li class="list-group-item">
          <div class="feed-body">
            <%= link_to post_show_path(@post.id) do %>
            <h3><%= @post.title %></h3>
                <% end %>
            <br>
            <p><%= @post.content %></p>
            <br>
            <div class="postFooter">
              <span class="postCity"><%= @post.city.name %>, <%= @post.city.country %> </span>

              <span class="postComments">Number of comments: <%= @post.comments.length %>,   <%= @post.time_difference %></span>

            <% if user_signed_in? %>
                <% if @post.user_id == current_user.id %>

                      <%= link_to post_edit_path(@post.id) do %>
                          <i class="fa fa-pencil fa-2x" aria-hidden="true"></i>
                      <% end %>

                      <%= link_to ('<i class="fa fa-trash fa-2x" aria-hidden="true"></i>').html_safe, post_delete_path(@post.id),
                                  method: 'delete',
                                  data: {
                                      :'sweet-alert-confirm' => "Are you sure you want to delete #{@post.title}?",
                                      :'confirm-button-text' => 'Delete',
                                      :'cancel-button-text' => 'Cancel',
                                      :'confirm-button-color' => '#D9534F',
                                      :'sweet-alert-type' => 'error',
                                      text: 'This cannot be undone.'
                                  } %>

                <% end %>
                <%= link_to comment_new_path(@post.id) do %>
                  <br>
                  <i class="fa fa-plus-square fa-2x" aria-hidden="true"></i>Add Comment
                <% end %>
            <% end %>
            </div>
          </div>
        </li>
      </div>
    </div>
  </div>
</div>
<br>

app/views/post/edit.html.erb
<div class="container">
  <div class="outer editForm">
    <h3>Edit your post</h3>
    <div class="row">
      <div class="inner editFormBox">
        <div class="">
          <%= bootstrap_form_for(@post, inline_errors: false, url: post_update_path(@post), method: :put) do |f| %>
              <%= f.alert_message "There was a problem updating your post:" %>
              <%= f.text_field :title, placeholder: @post.title %>
              <%= f.text_area :content, placeholder: @post.content %>
              <%= f.submit "Update Post", data: {
                  :'sweet-alert-confirm' => "Are you sure you want to edit this post?",
                  :'confirm-button-text' => 'Edit',
                  :'cancel-button-text' => 'Cancel',
                  :'confirm-button-color' => '#428BCA',
                  :'sweet-alert-type' => 'info',
                  text: 'This can be changed later.'
              } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/post/new.html.erb
<h1>Post#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

<%= bootstrap_form_for(@post, inline_errors: false, url: post_create_path) do |f| %>
  <%= f.alert_message "There was a problem creating your post:" %>
  <%= f.text_field :title %>
  <%= f.text_field :content %>
  <%= f.submit "Create Post", data: {
                  :'sweet-alert-confirm' => "Are you sure you want to create this post?",
                  :'confirm-button-text' => 'Create',
                  :'cancel-button-text' => 'Cancel',
                  :'confirm-button-color' => '#5CB85C',
                  :'sweet-alert-type' => 'success',
                  text: 'This can be edited later.'
                  } %>

<% end %>

app/views/post/show.html.erb
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<h3>
  <%= @post.title %>
</h3>
<h4>Written by <%= link_to user_show_path(@post.user) do %>
      <%= @post.user.username %>
  <% end %></h4>
<p>
  <%= @post.content %>
</p>
<div class="postFooter">
  <span class="postCity"><%= @post.city.name %>, <%= @post.city.country %> </span>
  <span class="postComments">Number of comments: <%= @post.comments.length %>,   <%= @post.time_difference %></span>
<% if user_signed_in? %>
  <% if @post.user_id == current_user.id %>
    <button type="button" class="btn btn-default">
      <%= link_to "Edit", post_edit_path(@post.id) %>
    </button>
    <button type="button" class="btn btn-default">
      <%= link_to "X",
          post_delete_path(@post.id),
          method: 'delete',
          data: {
            :'sweet-alert-confirm' => "Are you sure you want to delete #{@post.title}?",
            :'confirm-button-text' => 'Delete',
            :'cancel-button-text' => 'Cancel',
            :'confirm-button-color' => '#D9534F',
            :'sweet-alert-type' => 'error',
            text: 'This cannot be undone.'
            } %>
    </button>
  <% end %>
      <hr>
      </div>
<% end %>
  <br>
</div>
<h3>Comments:     <button class="btn btndefault">
  <%= link_to "Add Comment", comment_new_path(@post) %>
</button>
</h3>
<ul class="list-group">
    <% @post.comments.each do |comment| %>
      <li class="list-group-item">
        <p><%= comment.content %></p>
        <h4>Written by <%= link_to user_show_path(comment.user) do %>
              <%= comment.user.username %>
              <% end %>
          <% if user_signed_in? %>
            <% if current_user.id == comment.user.id %>
                <%= link_to ('<i class="fa fa-trash fa-2x" aria-hidden="true"></i>').html_safe,
                    "/posts/#{@post.id}/comments/#{comment.id}",
                    method: 'delete',
                    data: {
                      :'sweet-alert-confirm' => "Are you sure you want to delete this comment?",
                      :'confirm-button-text' => 'Delete',
                      :'cancel-button-text' => 'Cancel',
                      :'confirm-button-color' => '#D9534F',
                      :'sweet-alert-type' => 'error',
                      text: 'This cannot be undone.'
                      }
                    %>
            <% end %>
          <% end %>
        </h4>
      </li>
    <% end %>
  </ul>