config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get 'user/index'

  devise_for :users

  get 'cities/:city_id/post/new' => "post#new", as: "post_new"

  post 'cities/:city_id/post' => "post#create", as: "post_create"

  get 'posts/edit/:post_id' => "post#edit", as: "post_edit"

  get 'posts/:post_id' => "post#show", as: "post_show"

  put 'posts/:post_id' => "post#update", as: "post_update"

  delete 'posts/:post_id' => "post#delete", as: "post_delete"

  get 'city/index'

  get 'cities/:city_id' => "city#show", as: "city_show"

  get 'static_pages/home'

  get 'users' => "user#index"

  get 'users/profile' => "user#profile", as: "user_profile"

  get 'users/profile/edit' => "user#edit", as: "user_edit"

  get 'users/:user_id' => "user#show", as: "user_show"

  put 'users/:user_id' => "user#update", as: "user_update"
  
  get 'users/:user_id/following' => "user#following", as: "user_following"

  get 'users/:user_id/followers' => "user#followers", as: "user_followers"

  get 'posts/:post_id/comments/new' => "comments#new", as: "comment_new"

  post 'posts/:post_id/comments' => "comments#create", as: "comment_create"

  delete 'posts/:post_id/comments/:comment_id' => "comments#delete", as: "comment_delete"

  resources :bonds, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :username,
            presence: true,
            uniqueness: true

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  before_save :downcase_username
  before_save :default_name_and_img

  include FriendlyId
  friendly_id :username_downcase

  attr_accessor :login
  has_many :posts, dependent: :destroy
  has_many :cities, through: :posts

  has_many :active_bonds,  class_name: "Bond",
                           foreign_key: "follower_id",
                           dependent: :destroy
  has_many :passive_bonds, class_name: "Bond",
                           foreign_key: "followed_id",
                           dependent: :destroy

  has_many :following, through: :active_bonds, source: :followed
  has_many :followers, through: :passive_bonds

  has_many :comments

  geocoded_by :current_city
  after_validation :geocode
  
  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def downcase_username
    self.username_downcase = self.username.downcase
  end

  def sorted_posts
    posts = []
    self.following.each do |user|
      user.posts.each do |post|
        posts << post
      end  
    end
    posts.sort! {|x,y| y.created_at <=> x.created_at}
  end

  def default_name_and_img
    if !self.bio
      self.bio = 'Edit your profile and add a quick bio!'
    end
    if !self.img_url
      self.img_url = 'http://i.imgur.com/y4MoBvi.jpg'
    end
  end

  # BOND METHODS
  def follow(other_user)
    self.following << other_user
  end

  def unfollow(other_user)
    self.following.delete(other_user)
  end

  def following?(other_user)
    self.following.include?(other_user)
  end
  
  
  


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: [:profile, :edit, :feed]
  before_action :user_params, only: [:show, :following, :followers]
  def show
    @posts = @user.posts.paginate(:page => params[:page], per_page: 10)
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_update_params)
      redirect_to user_profile_path
    else
      render :edit
    end
  end
  
  def index
    @user = current_user
    @users = User.all
    @map_users = @users.reject {|user| !user.current_city}
    @hash = Gmaps4rails.build_markers(@map_users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow "#{user.first_name} #{user.last_name} \n #{user.username}"
    end
  end

  def profile
    @user = current_user
    @posts = @user.posts.paginate(:page => params[:page], per_page: 10)
  end

  def following
    @users = @user.following
  end
  
  def followers
    @users = @user.followers
  end
  
  

  private
    def user_params
      @user = User.friendly.find(params[:user_id].to_s.downcase)
    end

    def user_update_params
      params.require(:user)
            .permit(:first_name, :last_name, :bio, :img_url, :current_city)
    end

    

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_feed.html.erb
<div class="feed feed-header">
  <h3>What our Vagabonds are saying</h3>
</div>
<!--Posts Feed Template-->
<div class="container feed feed-container">
  <% @posts = current_user.sorted_posts %>
  <% @posts.each do |post| %>
    <%= render "post/post", collection: @post = post %>
  <% end %>
</div>

app/views/user/edit.html.erb
<h4>Edit User Profile</h4>


<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
      <%= bootstrap_form_for(@user, inline_errors: false, url: user_update_path(@user), method: :put) do |f| %>
        <%= f.alert_message "There was a problem updating your profile:" %>
        <%= f.text_field :first_name, placeholder: @user.first_name %>
        <%= f.text_field :last_name, placeholder: @user.last_name %>
        <%= f.text_field :current_city, placeholder: @user.current_city %>
        <%= f.text_area :img_url, placeholder: @user.img_url %>
        <%= f.text_area :bio, placeholder: @user.bio %>
        <%= f.submit "Update Profile", data: {
                  :'sweet-alert-confirm' => "Are you sure you want to edit your profile?",
                  :'confirm-button-text' => 'Edit',
                  :'cancel-button-text' => 'Cancel',
                  :'confirm-button-color' => '#428BCA',
                  :'sweet-alert-type' => 'info',
                  text: 'This can be changed later.'
                  } %>
      <% end %>
    </div>
  </div>
</div>

app/views/user/followers.html.erb
<h1><%= "User's Following #{@user.username}:"%></h1>

<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      
      <ul class="list-group">
        <% @users.each do |user| %>
          <li class="list-group-item">
            <%= link_to user.username, user_show_path(user) %>
          </li>
        <% end %>
      </ul>
      
    </div>
  </div>
</div>

app/views/user/following.html.erb
<h1><%= "User's Followed By #{@user.username}:"%></h1>

<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      
      <ul class="list-group">
        <% @users.each do |user| %>
          <li class="list-group-item">
            <%= link_to user.username, user_show_path(user) %>
          </li>
        <% end %>
      </ul>
      
    </div>
  </div>
</div>

app/views/user/index.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyAmYGEhY8eAhN0uAZIvLkKhDXSTuTt9ar4"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<%#basic bootstrap table, obviously modify later with styling or trash it%>
<h3 style="text-align: center;">All Users</h1>
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div style='width: 800px;'>
        <div id="usersMap" style='width: 800px; height: 400px;'></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>User</th>
              <th>Following</th>
              <th>Followers</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= link_to user.username, user_show_path(user) %>
                </td>
                <td>
                  <%= link_to user.following.count, user_following_path(user) %>
                </td>
                <td>
                  <%= link_to user.followers.count, user_followers_path(user) %>
                </td>
                <% if user_signed_in? %>
                  <td>
                    <% if user.id != current_user.id %>
                      <% if current_user.following?(user) %>
                        <%= form_for(@user.active_bonds.find_by(followed_id: user.id), 
                                    method: 'delete') do |f| %>
                          <%= f.submit "Unbond", class: "btn btn-danger" %>
                        <% end %>
                      <% else %>
                        <%= form_for(@user.active_bonds.build) do |f| %>
                          <div>
                            <%= hidden_field_tag :followed_id, user.id %>
                          </div>
                          <%= f.submit "Bond", class: "btn btn-primary" %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'usersMap'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/user/profile.html.erb
<div class="flex-container profile">
  <div class="userInfo">
    <% if @user.img_url %>
    <div class="userPicture" ><%= image_tag(@user.img_url, :class=> "profile_img img-rounded") %></div>
    <% end %>
        <div class="userDetails">
      <ul>
        <h3><%= @user.first_name %> <%= @user.last_name %></h3>
        <hr>
        <p><%= @user.username %></p>
        <h4>Vagabond since:</h4>
        <h5><%= @user.created_at.to_date%></h5>
        <h4>Current City:</h4>
        <h5><%= @user.current_city %></h5>
      </ul>

          <div class="userButtons">
            <%= button_to "Edit Profile",
                          user_edit_path,
                          :class => 'btn btn-info',
                          method: 'get' %>
          </div>
        </div>
  </div>


  <div class="posts ">
    <div class="userBio"><h3>Vagabond profile:</h3>
      <p> <%= @user.bio %></p>
      <% if @user.cities.uniq.length == 1 %>
          <p><%= "You have contributed to one city: #{@user.cities.uniq[0].name}" %></p>
      <% elsif @user.cities.uniq.length > 1 %>
          <p><%= "You have contrbuted to #{@user.cities.uniq.length} cities:" %></p>
          <ul>
              <% @user.cities.uniq.each do |city| %>
                  <li>
                      <%= city.name %>
                  </li>
              <% end %>
          </ul>
      <% end %>
    </div>
      <% if @posts.length != 0 %>
        <% @posts.each do |post|  %>
          <%= render "post/post_minimal", collection: @post = post %>
        <% end %>
      <% else %>
        <p><%= "#{@user.username} hasn't written any posts." %></p>
      <% end %>
      <br>
      <%= will_paginate @posts, :class => 'apple_pagination' %>

  </div>
</div>

app/views/user/show.html.erb
<div class="flex-container profile">
  <div class="userInfo">
    <% if @user.img_url %>
        <div class="userPicture" ><%= image_tag(@user.img_url, :class=> "profile_img img-rounded") %></div>
    <% end %>
    <div class="userDetails">
      <ul>
        <h3><%= @user.first_name %> <%= @user.last_name %></h3>
        <hr>
        <p><%= @user.username %></p>
        <h4>Vagabond since:</h4>
        <h5><%= @user.created_at.to_date%></h5>
        <h4>Current City:</h4>
        <h5><%= @user.current_city %></h5>
      </ul>
      <div class="userButtons">
      <% if user_signed_in? %>
          <% if @user.id != current_user.id %>
              <% if current_user.following?(@user) %>
                  <%= form_for(current_user.active_bonds.find_by(followed_id: @user.id),
                               method: 'delete') do |f| %>
                      <%= f.submit "UnBond", class: "btn btn-danger" %>
                  <% end %>
              <% else %>
                  <%= form_for(current_user.active_bonds.build) do |f| %>
                      <div>
                        <%= hidden_field_tag :followed_id, @user.id %>
                      </div>
                      <%= f.submit "Bond", class: "btn btn-success"%>
                  <% end %>
              <% end %>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>


  <div class="posts ">
    <div class="userBio"><h3>Vagabond profile:</h3>
        <p> <%= @user.bio %></p>
        <% if @user.cities.uniq.length == 1 %>
            <p><%= "This user has contributed to one city: #{@user.cities.uniq[0].name}" %></p>
        <% elsif @user.cities.uniq.length > 1 %>
            <p><%= "This user has contrbuted to #{@user.cities.uniq.length} cities:" %></p>
            <ul>
                <% @user.cities.uniq.each do |city| %>
                    <li>
                        <%= city.name %>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </div>
    <% if @posts.length != 0 %>
        <% @posts.each do |post|  %>
            <%= render "post/post_minimal", collection: @post = post %>
        <% end %>
    <% else %>
        <p><%= "#{@user.username} hasn't written any posts." %></p>
    <% end %>
    <br>
    <%= will_paginate @posts, :class => 'apple_pagination' %>

  </div>
</div>